export const FETCHING_STARTED = 'FETCHING_STARTED'
export const FETCHING_ENDED = 'FETCHING_ENDED'

export const FETCHING_BAND_SUCCESS = 'FETCHING_BAND_SUCCESS'
export const FETCHING_BAND_ERROR = 'FETCHING_BAND_ERROR'

export const FETCHING_ALBUM_NAME_SUCCESS = 'FETCHING_ALBUM_NAME_SUCCESS'
export const FETCHING_ALBUM_NAME_ERROR = 'FETCHING_ALBUM_NAME_ERROR'

export const FETCHING_ALBUM_COVER_SUCCESS = 'FETCHING_ALBUM_COVER_SUCCESS'
export const FETCHING_ALBUM_COVER_ERROR = 'FETCHING_ALBUM_COVER_ERROR'
